-- Tabla para alertas administrativas en Plataforma Espectral
-- Tipos permitidos:
--   1) nuevo_registro
--   2) formulario_completado

create table if not exists public.admin_notificaciones (
  id bigint generated by default as identity primary key,
  message text not null,
  tipo text not null check (tipo in ('nuevo_registro', 'formulario_completado')),
  created_at timestamptz not null default now()
);

create index if not exists idx_admin_notificaciones_created_at
  on public.admin_notificaciones (created_at desc);

alter table public.admin_notificaciones enable row level security;

-- Lectura solo para usuarios autenticados con rol admin en la tabla perfiles
create policy if not exists "admin puede leer notificaciones"
on public.admin_notificaciones
for select
to authenticated
using (
  exists (
    select 1
    from public.perfiles p
    where p.id = auth.uid()
      and lower(coalesce(p.role, '')) = 'admin'
  )
);

-- Inserción permitida a usuarios autenticados.
-- La app inserta eventos de registro y formulario completado.
create policy if not exists "usuarios autenticados pueden insertar notificaciones"
on public.admin_notificaciones
for insert
to authenticated
with check (
  tipo in ('nuevo_registro', 'formulario_completado')
  and char_length(trim(message)) > 0
);
